In [ ]:
from IPython.display import Image
from IPython.core.display import HTML 
%load_ext autoreload
%autoreload 2

# Python Tutorial
Be friends with Python:), what you are going to learn:
1. Data Types
2. Control Flow
3. Function/Class
4. Module → Here!

## Module
Modules split a longer prorgram into files to better maintain the program. We call those splited files 'modules'. You can further reuse your modules, or modules developed others, to develop new program.

### Import a module
1. 
```python
import random
```
2. 
```python
from random import randint
```
3. 
```python
from random import randint as ranit
```

In [ ]:
# import 'module_name'
# To use the function : 'module_name'.'function_name'
import random
print (random.random())
print (random.randint(1, 5))

In [ ]:
# from 'module_name' import 'function_A'name'
# To use function_a : 'function_A'name
from random import randint
print (randint())
#print (random(1, 5)) # Broken

In [1]:
# from 'module_name' import 'function_A'name' as 'alias'
# To use function_a : `alias`
from random import randint as ranit
print (ranit())
#print (randint()) # Broken

0.890691929441


### Write a Module
See `./Module`.

### Numpy
A Module for scientific computing in python.

In [16]:
import numpy as np

# Basic unit: Array
a = np.array([[1, 2, 3],[4, 5, 6]]) # Initialize an array
print (a)
print (type(a))
print ("{:<10}:{}".format("shape", a.shape)) # Print shape
print ("{:<10}:{}\n".format("data type", a.dtype)) # Print datatypes of elements

b = a.astype(np.float64) # Change datatypes
print (b)
print (type(a))
print ("{:<10}:{}".format("shape", b.shape))
print ("{:<10}:{}\n".format("data type", b.dtype))

print (a[0,0], a[0,0]) # Indexing
print (a[:-1, :-1]) # Slicing

[[1 2 3]
 [4 5 6]]
<type 'numpy.ndarray'>
shape     :(2, 3)
data type :int64

[[1. 2. 3.]
 [4. 5. 6.]]
<type 'numpy.ndarray'>
shape     :(2, 3)
data type :float64

(1, 1)
[[1 2]]


In [44]:
a = np.arange(9).reshape(3, 3).astype(np.float64)
b = np.arange(5, 14).reshape(3, 3).astype(np.float64)

print ("a", a)
print ("b", b)

print ("a-b", a-b) # Elementwise difference
print ("a+b", a+b) # Elementwise sum
print ("a*b", a*b) # Elementwise product
print ("a/b", a/b) # Elementwise dicition

print ("a*3", a*3) # Broadcast
tmp = np.array([1, 2, 3]).reshape(3, 1)
print ("tmp", tmp)
print ("a*tmp", a*tmp) # Broadcast

('a', array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]]))
('b', array([[ 5.,  6.,  7.],
       [ 8.,  9., 10.],
       [11., 12., 13.]]))
('a-b', array([[-5., -5., -5.],
       [-5., -5., -5.],
       [-5., -5., -5.]]))
('a+b', array([[ 5.,  7.,  9.],
       [11., 13., 15.],
       [17., 19., 21.]]))
('a*b', array([[  0.,   6.,  14.],
       [ 24.,  36.,  50.],
       [ 66.,  84., 104.]]))
('a/b', array([[0.        , 0.16666667, 0.28571429],
       [0.375     , 0.44444444, 0.5       ],
       [0.54545455, 0.58333333, 0.61538462]]))
('a*3', array([[ 0.,  3.,  6.],
       [ 9., 12., 15.],
       [18., 21., 24.]]))
('tmp', array([[1],
       [2],
       [3]]))
('a*tmp', array([[ 0.,  1.,  2.],
       [ 6.,  8., 10.],
       [18., 21., 24.]]))
